name: CI - Gestion Enquêtes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      #installation de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      #installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #initialisation de la base de données
      - name: Init SQLite database
        run: |
          python - <<EOF
          from database import init_db
          init_db()
          print("✅ Base SQLite initialisée")
          EOF

      #exécution des tests unitaire
      - name: Run unit tests
        run: |
          python -m unittest discover -s test
